# Generated by Django 3.2.5 on 2021-09-18 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media_to_media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.FileField(blank=True, null=True, upload_to='media_to_media/')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Media file to media files',
            },
        ),
        migrations.CreateModel(
            name='Media_to_text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.FileField(blank=True, null=True, upload_to='media_to_text/')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Media file to texts',
            },
        ),
        migrations.CreateModel(
            name='Text_to_media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='question', max_length=200)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Text to media files',
            },
        ),
        migrations.CreateModel(
            name='Text_to_text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=300)),
                ('question', models.CharField(max_length=300)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Text to texts',
            },
        ),
        migrations.CreateModel(
            name='Text_to_text_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=200)),
                ('correct_answer', models.BooleanField(default=False)),
                ('text_to_text_id', models.ForeignKey(blank=True, db_column='text_to_text_id', on_delete=django.db.models.deletion.CASCADE, related_name='text_to_text', to='reactives.text_to_text')),
            ],
            options={
                'verbose_name_plural': 'Text to text details',
            },
        ),
        migrations.CreateModel(
            name='Text_to_media_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_filename', models.FileField(blank=True, null=True, upload_to='text_to_media/')),
                ('correct_answer', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('text_to_media_id', models.ForeignKey(blank=True, db_column='text_to_media_id', on_delete=django.db.models.deletion.CASCADE, related_name='text_to_media', to='reactives.text_to_media')),
            ],
            options={
                'verbose_name_plural': 'Text to media files details',
            },
        ),
        migrations.CreateModel(
            name='Media_to_text_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=200)),
                ('correct_answer', models.BooleanField(default=False)),
                ('media_to_text_id', models.ForeignKey(blank=True, db_column='media_to_text_id', on_delete=django.db.models.deletion.CASCADE, related_name='media_to_text', to='reactives.media_to_text')),
            ],
            options={
                'verbose_name_plural': 'Media file to texts details',
            },
        ),
        migrations.CreateModel(
            name='Media_to_media_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_filename', models.FileField(blank=True, null=True, upload_to='Media_to_media_details/')),
                ('correct_answer', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('media_to_media_id', models.ForeignKey(blank=True, db_column='media_to_media_id', on_delete=django.db.models.deletion.CASCADE, related_name='media_to_media', to='reactives.media_to_media')),
            ],
            options={
                'verbose_name_plural': 'Media file to media files details',
            },
        ),
    ]
