# Generated by Django 3.2.3 on 2021-05-17 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Text_to_text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('correct_answer_id', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Text to texts',
            },
        ),
        migrations.CreateModel(
            name='Text_to_text_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=100)),
                ('text_to_text_id', models.ForeignKey(blank=True, db_column='text_to_text_id', on_delete=django.db.models.deletion.CASCADE, to='reactives.text_to_text')),
            ],
            options={
                'verbose_name_plural': 'Text to text details',
            },
        ),
    ]
