# Generated by Django 3.2.3 on 2021-05-17 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactives', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text_to_text',
            name='correct_answer_id',
        ),
        migrations.AddField(
            model_name='text_to_text_detail',
            name='correct_answer',
            field=models.BooleanField(default=False),
        ),
    ]
