# Generated by Django 3.2.3 on 2021-05-17 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reactives', '0002_auto_20210517_0206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text_to_media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.FileField(blank=True, null=True, upload_to='text_to_media/')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Text to media files',
            },
        ),
        migrations.CreateModel(
            name='text_to_media_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=100)),
                ('correct_answer', models.BooleanField(default=False)),
                ('text_to_media_id', models.ForeignKey(blank=True, db_column='text_to_media_id', on_delete=django.db.models.deletion.CASCADE, to='reactives.text_to_media')),
            ],
            options={
                'verbose_name_plural': 'Text to media files details',
            },
        ),
    ]
