# Generated by Django 3.2.3 on 2021-05-17 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reactives', '0003_text_to_media_text_to_media_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media_to_media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.FileField(blank=True, null=True, upload_to='media_to_media/')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Media file to media files',
            },
        ),
        migrations.CreateModel(
            name='Media_to_text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.FileField(blank=True, null=True, upload_to='media_to_text/')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Media file to texts',
            },
        ),
        migrations.RemoveField(
            model_name='text_to_media',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='text_to_media_detail',
            name='answer',
        ),
        migrations.AddField(
            model_name='text_to_media',
            name='question',
            field=models.CharField(default='question', max_length=100),
        ),
        migrations.AddField(
            model_name='text_to_media_detail',
            name='answer_filename',
            field=models.FileField(blank=True, null=True, upload_to='text_to_media/'),
        ),
        migrations.CreateModel(
            name='Media_to_text_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=100)),
                ('correct_answer', models.BooleanField(default=False)),
                ('media_to_text_id', models.ForeignKey(blank=True, db_column='media_to_text_id', on_delete=django.db.models.deletion.CASCADE, to='reactives.media_to_text')),
            ],
            options={
                'verbose_name_plural': 'Media file to texts details',
            },
        ),
        migrations.CreateModel(
            name='Media_to_media_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_filename', models.FileField(blank=True, null=True, upload_to='Media_to_media_details/')),
                ('correct_answer', models.BooleanField(default=False)),
                ('media_to_media_id', models.ForeignKey(blank=True, db_column='media_to_text_id', on_delete=django.db.models.deletion.CASCADE, to='reactives.media_to_media')),
            ],
            options={
                'verbose_name_plural': 'Media file to media files details',
            },
        ),
    ]
