# Generated by Django 3.2.3 on 2021-06-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactives', '0004_auto_20210517_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='media_to_media',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='media_to_text',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
