# Generated by Django 3.2.5 on 2021-07-28 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactives', '0005_auto_20210626_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='media_to_media_detail',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='media_to_text_detail',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='text_to_media_detail',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
