# Generated by Django 3.2.5 on 2021-08-01 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reactives', '0006_auto_20210728_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media_to_media_detail',
            name='media_to_media_id',
            field=models.ForeignKey(blank=True, db_column='media_to_media_id', on_delete=django.db.models.deletion.CASCADE, related_name='media_to_media', to='reactives.media_to_media'),
        ),
    ]
