# Generated by Django 3.2.5 on 2021-08-01 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reactives', '0007_alter_media_to_media_detail_media_to_media_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media_to_text_detail',
            name='media_to_text_id',
            field=models.ForeignKey(blank=True, db_column='media_to_text_id', on_delete=django.db.models.deletion.CASCADE, related_name='media_to_text', to='reactives.media_to_text'),
        ),
        migrations.AlterField(
            model_name='text_to_media_detail',
            name='text_to_media_id',
            field=models.ForeignKey(blank=True, db_column='text_to_media_id', on_delete=django.db.models.deletion.CASCADE, related_name='text_to_media', to='reactives.text_to_media'),
        ),
        migrations.AlterField(
            model_name='text_to_text_detail',
            name='text_to_text_id',
            field=models.ForeignKey(blank=True, db_column='text_to_text_id', on_delete=django.db.models.deletion.CASCADE, related_name='text_to_text', to='reactives.text_to_text'),
        ),
    ]
