# Generated by Django 3.2.5 on 2021-08-01 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reactives', '0008_auto_20210801_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media_to_text_detail',
            name='description',
        ),
    ]
