# Generated by Django 3.2.5 on 2021-08-26 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactives', '0010_auto_20210809_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='text_to_text',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='text_to_text',
            name='question',
            field=models.CharField(max_length=300),
        ),
    ]
