# Generated by Django 3.2.5 on 2021-09-18 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reactives', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('chapter_image', models.FileField(blank=True, null=True, upload_to='chapter/')),
            ],
            options={
                'verbose_name_plural': 'Chapters',
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('chapter_id', models.ForeignKey(blank=True, db_column='chapter_id', on_delete=django.db.models.deletion.CASCADE, to='exercises.chapter')),
            ],
            options={
                'verbose_name_plural': 'Exercises',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Levels',
            },
        ),
        migrations.CreateModel(
            name='Reactive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Reactives',
            },
        ),
        migrations.CreateModel(
            name='Exercise_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, default=1)),
                ('experience', models.IntegerField(blank=True, default=100)),
                ('active', models.BooleanField(default=True)),
                ('exercise_id', models.ForeignKey(blank=True, db_column='exercise_id', on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise')),
                ('exercise_id_Media_to_media', models.ForeignKey(blank=True, db_column='exercise_id_Media_to_media', null=True, on_delete=django.db.models.deletion.CASCADE, to='reactives.media_to_media')),
                ('exercise_id_Media_to_text', models.ForeignKey(blank=True, db_column='exercise_id_Media_to_text', null=True, on_delete=django.db.models.deletion.CASCADE, to='reactives.media_to_text')),
                ('exercise_id_Text_to_media', models.ForeignKey(blank=True, db_column='exercise_id_Text_to_media', null=True, on_delete=django.db.models.deletion.CASCADE, to='reactives.text_to_media')),
                ('exercise_id_Text_to_text', models.ForeignKey(blank=True, db_column='exercise_id_Text_to_text', null=True, on_delete=django.db.models.deletion.CASCADE, to='reactives.text_to_text')),
                ('reactive_id', models.ForeignKey(blank=True, db_column='reactive_id', on_delete=django.db.models.deletion.CASCADE, to='exercises.reactive')),
            ],
            options={
                'verbose_name_plural': 'Exercises Details',
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='level_id',
            field=models.ForeignKey(blank=True, db_column='level_id', on_delete=django.db.models.deletion.CASCADE, to='exercises.level'),
        ),
    ]
