# Generated by Django 3.2.3 on 2021-05-17 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise_detail',
            name='order',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
