# Generated by Django 3.2.3 on 2021-05-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_auto_20210517_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise_detail',
            name='experience',
            field=models.IntegerField(blank=True, default=100),
        ),
        migrations.AlterField(
            model_name='exercise_detail',
            name='order',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
