# Generated by Django 3.2.3 on 2021-06-09 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_auto_20210517_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='chapter_image',
            field=models.FileField(blank=True, null=True, upload_to='chapter/'),
        ),
    ]
