# Generated by Django 3.2.3 on 2021-06-25 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reactives', '0004_auto_20210517_1358'),
        ('exercises', '0006_auto_20210625_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise_detail',
            name='exercise_id_Media_to_media',
            field=models.ForeignKey(blank=True, db_column='exercise_id_Media_to_media', null=True, on_delete=django.db.models.deletion.CASCADE, to='reactives.media_to_media'),
        ),
        migrations.AlterField(
            model_name='exercise_detail',
            name='exercise_id_Media_to_text',
            field=models.ForeignKey(blank=True, db_column='exercise_id_Media_to_text', null=True, on_delete=django.db.models.deletion.CASCADE, to='reactives.media_to_text'),
        ),
        migrations.AlterField(
            model_name='exercise_detail',
            name='exercise_id_Text_to_media',
            field=models.ForeignKey(blank=True, db_column='exercise_id_Text_to_media', null=True, on_delete=django.db.models.deletion.CASCADE, to='reactives.text_to_media'),
        ),
        migrations.AlterField(
            model_name='exercise_detail',
            name='exercise_id_Text_to_text',
            field=models.ForeignKey(blank=True, db_column='exercise_id_Text_to_text', null=True, on_delete=django.db.models.deletion.CASCADE, to='reactives.text_to_text'),
        ),
    ]
