# Generated by Django 3.2.3 on 2021-05-17 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_exercise_detail_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='level',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='reactive',
            old_name='descripcion',
            new_name='description',
        ),
    ]
